# Generated by Django 4.1.5 on 2023-04-22 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useralgoritmrun',
            old_name='created_on',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='useralgoritmrun',
            name='algorithm_id',
        ),
        migrations.RemoveField(
            model_name='useralgoritmrun',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='useralgoritmrun',
            name='user_id',
        ),
        migrations.AddField(
            model_name='useralgoritmrun',
            name='algorithm_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useralgoritmrun',
            name='result',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useralgoritmrun',
            name='status',
            field=models.CharField(default='finished', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useralgoritmrun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useralgoritmrun',
            name='user_email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
