# Generated by Django 4.1.5 on 2023-04-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_on_useralgoritmrun_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralgoritmrun',
            name='user_email',
            field=models.EmailField(max_length=255),
        ),
    ]
